jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin"
  numExecutors: 2
  mode: NORMAL

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

security:
  scriptApproval:
    approvedSignatures:
      - "method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods println java.lang.Object java.lang.Object"

jobs:
  - script: >
      job('seed-job-jenkins-ci-test') {
      scm {
          git {
            remote {
              url('file:///jenkins-controller')
            }
            branch('main')
          }
        }
        steps {
          dsl {
            external('scripts/create_job_dsl.groovy')
            removeAction('DELETE')
            removeViewAction('DELETE')
            ignoreExisting(false)
          }
        }
      }
